language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - mysql
before_script:
  # install behat, mink etc
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - git submodule update --init --recursive
  - mkdir -p app/cache app/logs
  - chmod 777 app/cache app/logs
  - app/console cache:warmup --env=test
  - chmod -R 777 app/cache app/logs
  # db setup
  - app/console doctrine:database:create --env=test
  - app/console doctrine:schema:create --env=test
  # webserver setup
  - bin/start_server &
  - sleep 3
script:
  - bin/behat --config application/tests/behat.yml
  - bin/phpunit -c app
