Swop\ConfigStore\Model\ConfigItem:
    exclusion_policy: ALL
    access_type: public_method
    read_only: true
    properties:
        app:
            expose: true
            type: Swop\ConfigStore\Model\App
            groups: [ConfigItem]
        key:
            expose: true
            type: string
            groups: [ConfigItem, App, Diff]
        value:
            expose: true
            type: string
            groups: [ConfigItem, App, Diff]
