security:
    encoders:
        Swop\ConfigStore\Model\User: sha512
    providers:
        api_apps:
            id: swop.bundle.config_store.security.user.api_key_based_app_provider
        users:
            id: swop.bundle.config_store.security.user.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/myconfig
            stateless: true
            simple_preauth:
                authenticator: swop.bundle.config_store.security.authenticator.api_key
                provider: api_apps

        admin:
            provider: users
            pattern: ^/admin
            form_login:
                check_path: login_check
                login_path: user_login
                default_target_path: admin_homepage
                always_use_default_target_path: true
                username_parameter: "login[username]"
                password_parameter: "login[password]"
                csrf_parameter: "login[_token]"
                intention: "login"
                csrf_provider: "form.csrf_provider"
            logout:
                path: logout
                target: user_login
            remember_me:
                key: "%secret%"
                remember_me_parameter: "login[remember_me]"
            switch_user: true
            anonymous: true
    access_control:
        - { path: ^/myconfig, roles: ROLE_APP }
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
