admin_homepage:
    path: /
    defaults: { _controller: "SwopConfigStoreBundle:Admin/Home:home" }

admin_apps:
    prefix: /apps
    resource: 'admin/apps.yml'

admin_groups:
    prefix: /groups
    resource: 'admin/groups.yml'
